### ISSUE TITLE
Armor Trims Backport

### ISSUE THREAD

**Issue by Hipposgrumm** [Apollounknowndev/trimmable-tools#1]
I have released Armor Trims Backport 1.2 for 1.19.2, which includes the ability to add custom trimmable items (with associated textures) using the API (which will require an actual mod for due to its nature).
Since you opened Issue [#4](https://github.com/Hipposgrumm/armor-trims/issues/4) on my Bug Tracker asking for the feature, I feel it fitting to leave one on yours stating that it has been implemented.

Due to the recent issue on CurseForge (that you have probably heard about), the mod will probably take up to a day to be added. However, the mod **CAN** already be found on Modrinth ([here](https://modrinth.com/mod/armor-trims/version/1.2)).

If you need my help with creating the integrated mod, you can ask me (the API might not always be clear; it's my first time doing something like it after all).

**Comment by Hipposgrumm** [comment]
I should probably tell you that I modified the API slightly because I noticed a bug that requires some corrections in the API.
If you want the mod to look as good as possible you might want to install the new version of 1.2.

**Comment by Hipposgrumm** [comment]
It’s been a while and I haven’t heard from you. Are you still working on this and need help? If you need help, [I now have a Discord server where you can ask](https://discord.gg/tEyg8GJw48).

**Comment by Apollounknowndev** [comment]
Haven't gotten around to the backport just yet, will work on it soon

**Comment by Hipposgrumm** [comment]
Hello, I was wondering if you were either busy or had forgotten, but I want to know if you plan to/are working on this. This is just a follow up and there is no rush.

**Comment by Hipposgrumm** [comment]
I know this thread is very old but I have finally released a new version of the mod and wanted to let you know in case you were still interested.
