### ISSUE TITLE
Trimed but no texture in game

### ISSUE THREAD

**Issue by FelixAgairu** [Apollounknowndev/trimmable-tools#10]
MC 1.21.1
Fabric 0.16.5
Trimmable Tools 2.0.3

![image](https://github.com/user-attachments/assets/3ea47e2d-ccf5-4b22-912d-b4082a276b46)
![image](https://github.com/user-attachments/assets/41e10406-32f6-4403-96ba-6c0a1798aa3b)

**Comment by Apollounknowndev** [comment]
Can you attach your mod/resource pack list?

**Comment by EtoKobato** [comment]
[Client Spark](https://spark.lucko.me/2cisBYhssh)
[Server Spark](https://spark.lucko.me/PAw2BXrmxc)

Sorry, I just change trimmable-tools to others

I found that may the datapack issue, with many of Datapack Mod:

if i install mod version
  client not works well: no, missing translation and texture
  but all function work
if install datapack and resource pack version
  everything seems good.

**Comment by u0398** [comment]
Support for [Deeper and Darker](https://modrinth.com/mod/deeperdarker) would be nice.
