### ISSUE TITLE
Deeper and Darker tools compatibility

### ISSUE THREAD

**Issue by u0398** [Apollounknowndev/trimmable-tools#12]
I am trying to add Deeper and Darker tools compatibility using your instructions. For testing I'm just adding files to the Trimmable Tools jar.

As an example, for the resonarium sword I added this line to `data\trimmable_tools\tags\item\trimmable_tools.json`:

`"deeperdarker:resonarium_sword"`

And created `assets\minecraft\models\item\resonarium_sword.json` with these contents:

```
{
  "trimmable_tools:material": "diamond",
  "trimmable_tools:tool_type": "sword",
  "parent": "minecraft:item/handheld",
  "textures": {
    "layer0": "deeperdarker:item/resonarium_sword"
  }
}
```

The trims apply correctly in the smithing table, but the textures do not display. What am I missing?

**Comment by Apollounknowndev** [comment]
the `resonarium_sword` item model would be in the `deeperdarker` namespace, not the `minecraft` namespace.

**Comment by u0398** [comment]
Thank you! Rookie mistake for sure.
