### ISSUE TITLE
Does not work on 1.21. Tools are still trimmable (and compatible with mods like trims expanded), but the trim just doesn't show on screen. 

### ISSUE THREAD

**Issue by Th3Dandy** [Apollounknowndev/trimmable-tools#14]
I also tried without resource packs and without any mod, still nothing. One of the best mods, if you can fix this that would be great. I love the work, thanks.
![image](https://github.com/user-attachments/assets/b0dc82a2-bed2-4d88-980f-7f38524d10ac)
![image](https://github.com/user-attachments/assets/c59e9867-90fd-4250-b486-6f2d13dadc71)

**Comment by Th3Dandy** [comment]
Thanks. In solved issues, someone mentioned that the Ressource pack never loads in the .jar and needs to be downloaded manually along the datapack from here https://modrinth.com/datapack/trimmable-tools/version/1.0.5.

**Comment by Apollounknowndev** [comment]
The resource pack in v2 should load fine.

**Comment by Th3Dandy** [comment]
From what I understand v2 is still in progress ? What does it bring ? If you need a tester by the way, I'm here. Well you can always just boot up Minecraft yourself, but getting exterior opinions is an extra +

**Comment by Apollounknowndev** [comment]
The mod version of v2 has been done for some time now, it's the datapack version still in progress.
