### ISSUE TITLE
All trims are the same, might the color or trim change

### ISSUE THREAD

**Issue by Th3Dandy** [Apollounknowndev/trimmable-tools#15]
Title really. In addition to the ressource pack not running in the .jar and needing to be installed manually, any trim looks like this 
![image](https://github.com/user-attachments/assets/d565fbd2-2d79-4546-ab61-464f48a5e915)

Up is copper silence trim, down is diamond flow trim. Even with other (and without, I tested with only this mod and no resource packs) datapacks like trims expanded display the same trim.

**Comment by Apollounknowndev** [comment]
What game version/Trimmable Tools version are you on?

**Comment by Th3Dandy** [comment]
I'm on 1.21, fabric loader. Mod version is the datapack you get by downloading using the download button on modrinth and chosing fabric 1.21, + the corresponding resource pack file in https://modrinth.com/datapack/trimmable-tools/versions .

**Comment by Apollounknowndev** [comment]
Don't use the resource pack from v1. Only the mod from v2 should be necessary.

**Comment by Th3Dandy** [comment]
![image](https://github.com/user-attachments/assets/a1b37de3-aa75-4088-b4da-851b4e7d0376)

https://github.com/user-attachments/assets/087bc2e1-7d85-41c5-9871-30e5c118d63c

Nope. Still nothing.

**Comment by Th3Dandy** [comment]
Oh sorry. Don't worry everything actually works fine. For some reason, enabling and disabling a Vanilla Tweaks item stitching fix rpack worked when it didn't before. And you don't need the resource pack too.
