### ISSUE TITLE
Compatability Request: More Tool Variants, Mythic Metals, Betterend, Better Nether, All the Trims.

### ISSUE THREAD

**Issue by Sinogard** [Apollounknowndev/trimmable-tools#16]
These mods add new materials for the vanilla tools to be made from and id like to make them trimmable and use their materials as a trimmable material. Is it possible to make this compatible with "All The Trims?" I'm willing to learn how to do any code and art work this request might need myself but I'm very much a beginner at this and would appreciate assistance if i get stuck on something for a week (looking at you my failed backpack mod).

**Comment by Apollounknowndev** [comment]
Mods that add new tool tiers to vanilla tools -> Compat possible, all tool model files need to be edited to make this happen.
![image](https://github.com/user-attachments/assets/180a4b0e-30be-499f-8734-7554cd591f1e)

Mods that add new trim materials -> see [here](https://github.com/Apollounknowndev/trimmable-tools/wiki/Custom-trim-materials)

Mods that add new trim patterns / new tool types -> You have to make the textures yourself, no guide for it.

All the Trims -> No.

**Comment by Sinogard** [comment]
got it. would I need to add something like this to the individual mods themselves or to Trimmable Tools for each added tool?

**Comment by Th3Dandy** [comment]
They add new materials ? You might want to try https://modrinth.com/datapack/trims-expanded, fully compatible with this one

**Comment by Sinogard** [comment]
They use vanilla materials by default. "all the trims" makes every item a trim material and creates the color pattern in runtime based on the colors present in the item itself.

**Comment by Th3Dandy** [comment]
Ohhhh. That seems very cool then. From what I understand the pack exists but is not compatible with this one yet ? Well update me on it if you can, I'm learning Java right now, maybe in a good 10 years I could help :P

**Comment by Sinogard** [comment]
Got started tonight. The first step ive gathered is to update code in trimmable_tools.json with the appropriate items i wish to make trimmable right?
<details>
<summary> new code in trimmable_tools.json </summary>
{
  "values": [
    "minecraft:diamond_sword",
    "minecraft:stone_sword",
    "minecraft:golden_sword",
    "minecraft:netherite_sword",
    "minecraft:wooden_sword",
    "minecraft:iron_sword",
    "mythicmetals:copper_sword",
    "mythicmetals:aquarium_sword",
    "mythicmetals:banglum_sword",
    "betterend:thallasium_sword",
    "mythicmetals:quadrillum_sword",
    "mythicmetals:bronze_sword",
    "betternether:cincinnacite_sword",
    "betternether:cincinnacite_diamond_sword",
    "mythicmetals:midas_gold_sword",
    "betternether:nether_ruby_sword",
    "betternether:fireruby_sword",
    "mythicmetals:osmium_sword",
    "mythicmetals:steel_sword",
    "mythicmetals:durasteel_sword",
    "mythicmetals:kyber_sword",
    "mythicmetals:legendary_bengal_sword",
    "mythicmetals:carmot_sword",
    "betterend:terminite_sword",
    "mythicmetals:tidesinger_sword",
    "mythicmetals:runite_sword",
    "mythicmetals:promethium_sword",
    "mythicmetals:paladium_sword",
    "mythicmetals:adamantite_sword",
    "mythicmetals:mythril_sword",
    "mythicmetals:orichalcum_sword",
    "mythicmetals:hallowed_sword",
    "betterend:aeternium_sword",
    "mythicmetals:celestium_sword",
    "mythicmetals:metallurgium_sword",
    "mythicmetals:stormyx_sword",
    "mythicmetals:star_platinum_sword",
    "minecraft:diamond_axe",
    "minecraft:stone_axe",
    "minecraft:golden_axe",
    "minecraft:netherite_axe",
    "minecraft:wooden_axe",
    "minecraft:iron_axe",
    "mythicmetals:copper_axe",
    "mythicmetals:aquarium_axe",
    "mythicmetals:banglum_axe",
    "betterend:thallasium_axe",
    "mythicmetals:quadrillum_axe",
    "mythicmetals:bronze_axe",
    "betternether:cincinnacite_axe",
    "betternether:cincinnacite_diamond_axe",
    "mythicmetals:midas_gold_axe",
    "betternether:nether_ruby_axe",
    "betternether:fireruby_axe",
    "mythicmetals:osmium_axe",
    "mythicmetals:steel_axe",
    "mythicmetals:durasteel_axe",
    "mythicmetals:kyber_axe",
    "mythicmetals:legendary_bengal_axe",
    "mythicmetals:carmot_axe",
    "betterend:terminite_axe",
    "mythicmetals:tidesinger_axe",
    "mythicmetals:runite_axe",
    "mythicmetals:promethium_axe",
    "mythicmetals:paladium_axe",
    "mythicmetals:adamantite_axe",
    "mythicmetals:mythril_axe",
    "mythicmetals:orichalcum_axe",
    "mythicmetals:hallowed_axe",
    "betterend:aeternium_axe",
    "mythicmetals:celestium_axe",
    "mythicmetals:metallurgium_axe",
    "mythicmetals:stormyx_axe",
    "mythicmetals:star_platinum_axe",
    "minecraft:diamond_pickaxe",
    "minecraft:stone_pickaxe",
    "minecraft:golden_pickaxe",
    "minecraft:netherite_pickaxe",
    "minecraft:wooden_pickaxe",
    "minecraft:iron_pickaxe",
    "mythicmetals:copper_pickaxe",
    "mythicmetals:aquarium_pickaxe",
    "mythicmetals:banglum_pickaxe",
    "betterend:thallasium_pickaxe",
    "mythicmetals:quadrillum_pickaxe",
    "mythicmetals:bronze_pickaxe",
    "betternether:cincinnacite_pickaxe",
    "betternether:cincinnacite_diamond_pickaxe",
    "mythicmetals:midas_gold_pickaxe",
    "betternether:nether_ruby_pickaxe",
    "betternether:fireruby_pickaxe",
    "mythicmetals:osmium_pickaxe",
    "mythicmetals:steel_pickaxe",
    "mythicmetals:durasteel_pickaxe",
    "mythicmetals:kyber_pickaxe",
    "mythicmetals:legendary_bengal_pickaxe",
    "mythicmetals:carmot_pickaxe",
    "betterend:terminite_pickaxe",
    "mythicmetals:tidesinger_pickaxe",
    "mythicmetals:runite_pickaxe",
    "mythicmetals:promethium_pickaxe",
    "mythicmetals:paladium_pickaxe",
    "mythicmetals:adamantite_pickaxe",
    "mythicmetals:mythril_pickaxe",
    "mythicmetals:orichalcum_pickaxe",
    "mythicmetals:hallowed_pickaxe",
    "betterend:aeternium_pickaxe",
    "mythicmetals:celestium_pickaxe",
    "mythicmetals:metallurgium_pickaxe",
    "mythicmetals:stormyx_pickaxe",
    "mythicmetals:star_platinum_pickaxe",
    "minecraft:diamond_shovel",
    "minecraft:stone_shovel",
    "minecraft:golden_shovel",
    "minecraft:netherite_shovel",
    "minecraft:wooden_shovel",
    "minecraft:iron_shovel",
    "mythicmetals:copper_shovel",
    "mythicmetals:aquarium_shovel",
    "mythicmetals:banglum_shovel",
    "betterend:thallasium_shovel",
    "mythicmetals:quadrillum_shovel",
    "mythicmetals:bronze_shovel",
    "betternether:cincinnacite_shovel",
    "betternether:cincinnacite_diamond_shovel",
    "mythicmetals:midas_gold_shovel",
    "betternether:nether_ruby_shovel",
    "betternether:fireruby_shovel",
    "mythicmetals:osmium_shovel",
    "mythicmetals:steel_shovel",
    "mythicmetals:durasteel_shovel",
    "mythicmetals:kyber_shovel",
    "mythicmetals:legendary_bengal_shovel",
    "mythicmetals:carmot_shovel",
    "betterend:terminite_shovel",
    "mythicmetals:tidesinger_shovel",
    "mythicmetals:runite_shovel",
    "mythicmetals:promethium_shovel",
    "mythicmetals:paladium_shovel",
    "mythicmetals:adamantite_shovel",
    "mythicmetals:mythril_shovel",
    "mythicmetals:orichalcum_shovel",
    "mythicmetals:hallowed_shovel",
    "betterend:aeternium_shovel",
    "mythicmetals:celestium_shovel",
    "mythicmetals:metallurgium_shovel",
    "mythicmetals:stormyx_shovel",
    "mythicmetals:star_platinum_shovel",
    "minecraft:diamond_hoe",
    "minecraft:stone_hoe",
    "minecraft:golden_hoe",
    "minecraft:netherite_hoe",
    "minecraft:wooden_hoe",
    "minecraft:iron_hoe",
    "mythicmetals:copper_hoe",
    "mythicmetals:aquarium_hoe",
    "mythicmetals:banglum_hoe",
    "betterend:thallasium_hoe",
    "mythicmetals:quadrillum_hoe",
    "mythicmetals:bronze_hoe",
    "betternether:cincinnacite_hoe",
    "betternether:cincinnacite_diamond_hoe",
    "mythicmetals:midas_gold_hoe",
    "betternether:nether_ruby_hoe",
    "betternether:fireruby_hoe",
    "mythicmetals:osmium_hoe",
    "mythicmetals:steel_hoe",
    "mythicmetals:durasteel_hoe",
    "mythicmetals:kyber_hoe",
    "mythicmetals:legendary_bengal_hoe",
    "mythicmetals:carmot_hoe",
    "betterend:terminite_hoe",
    "mythicmetals:tidesinger_hoe",
    "mythicmetals:runite_hoe",
    "mythicmetals:promethium_hoe",
    "mythicmetals:paladium_hoe",
    "mythicmetals:adamantite_hoe",
    "mythicmetals:mythril_hoe",
    "mythicmetals:orichalcum_hoe",
    "mythicmetals:hallowed_hoe",
    "betterend:aeternium_hoe",
    "mythicmetals:celestium_hoe",
    "mythicmetals:metallurgium_hoe",
    "mythicmetals:stormyx_hoe",
    "mythicmetals:star_platinum_hoe"
  ]
}
</details>

**Comment by Sinogard** [comment]
so it would appear that all the trims does affect this mod without any changes. only issue is that it doesnt pull the texture and therefore doesn't color it. I'm asking how to correct this on their issue tracker. if i can get a answer i might be able to add this or at least report back what they say in regards to making it function.

![Screenshot 2024-11-28 093011](https://github.com/user-attachments/assets/17a52f19-20a4-4f10-9781-bdcca4e7e6fa)

**Comment by Apollounknowndev** [comment]
> Mods that add new tool tiers to vanilla tools -> Compat possible, all tool model files need to be edited to make this happen. 

Quick little update on this: As of 2.0.5 (releasing very soon), this will no longer be needed as mods with new tools in the relevant tool tags will natively have tool trim support.

That being said, Mythic Metals will have some minor texture issues due to how the tools are placed in the 16x16 texture grid. If someone wants to move around the textures to fix the issue, be my guest.
![image](https://github.com/user-attachments/assets/b2112091-fc26-49c8-96f0-d67c89d8e2c0)

If you have any further questions/bugs to report, please create a new issue.
