### ISSUE TITLE
Stone tools not included in current version.

### ISSUE THREAD

**Issue by gspradley** [Apollounknowndev/trimmable-tools#18]
First time downloading, but after testing in a new world, stone tools will receive/use the trim, but the item texture doesn't change.  Is this as intended, or were the stone tool textures not included by accident?

![Stone pickaxe](https://github.com/user-attachments/assets/38813cb6-e6aa-4c0f-8ed8-3da9e8493ed2)

**Comment by Apollounknowndev** [comment]
Accidental exclusion, resolved in v2.0.4.
