### ISSUE TITLE
how to add fixed textures for mythic metals?

### ISSUE THREAD

**Issue by Sinogard** [Apollounknowndev/trimmable-tools#20]
I'm hoping to knock this out this week. so I just need to know how to add new textures to the different sized textures. I'm more than willing to make them / edit them to work. 

Tomorrow i will 
1. create the new edited textures. 
2. add them to a datapack (I presume this is the prefererd method as edditing the mod might cause issues. if you'd like to add them baseline to the mod I can send them over when they are done.)
2a. Could you tell me how to do it?
3. Test them and make sure they are correct.

Thank you for everything. I love the mod!

**Comment by Apollounknowndev** [comment]
Fixing the textures with Mythic Metals will just require a separate resource pack. The issue is that Mythic Metals places its textures in the 16x16 area incorrectly relative to vanilla tools, as you can see here.
![image](https://github.com/user-attachments/assets/6c717eb0-c590-4166-b444-c55277edf91e)
All a fix would have to do is move those tool textures down so the tools line up with them.

**Comment by Sinogard** [comment]
Well that's an easy fix. I'll get that done real quick and upload that resource pack on modrinth. Should i post that here for those interested or would you rather i not?

**Comment by Sinogard** [comment]
it seems that some of the textures in mythic metals utilize the full 16 x 16 square. expanding them to a 17 x 17 or to 17 x 18 causes the texture of the trim to... apply stretched in the center. causes the texture to not line up. 
![Screenshot 2024-12-08 175029](https://github.com/user-attachments/assets/263f6f1b-f03e-4b2a-a711-47a03ec96b77)
This is an issue that can be fixed by creating a new texture from scratch that reduces it total size by 1 in general. this is unfortunately half of the textures. The fix is relatively quick if not a bit tedious. by reducing the size of the handle i can get the texture to conform to a 16 x 16  square in a way for the trims to apply correctly. it just makes the pickaxes not have as much handle. Im not sure if id notice a difference if i didn't know but since i do they feel short, haha.
![Screenshot 2024-12-08 181051](https://github.com/user-attachments/assets/1d59985e-245d-468d-8ba6-7845d8a5675d)

**Comment by Sinogard** [comment]
the first rough resource pack is done. im unsure if i will edit together a more vanilla friendly version at this time but for now heres the results.
![gallery](https://github.com/user-attachments/assets/c988bd64-e5dd-48e5-b22a-c285ab31c31c)

link for now as ive not heard either way on whether i should or not. Feel free to remove it if you wish.
https://modrinth.com/resourcepack/mmtsc
