### ISSUE TITLE
Resourcepack does not load from the mod .jar

### ISSUE THREAD

**Issue by LessThanBenji** [Apollounknowndev/trimmable-tools#3]
The required resourcepack does not deploy from the .jar (mod) file version. I had a peek inside the .jar (v1.0.4 for 1.20.2) and can see that the resources/textures are there, but they aren't formatted as a resourcepack and hence don't load, let alone show up in the in-game resourcepack selection screen.

I have gotten around this issue by seperately downloading the resourcepack from the datapack version's download page on Modrinth (https://modrinth.com/datapack/trimmable-tools/version/1.0.5) and installing+applying it manually, works fine now.

Just a heads up to you and anyone else who might've been experiencing the same problem. Amazing work btw, the tools do look awesome.

**Comment by Th3Dandy** [comment]
Thank you so much ! Was wondering why it wasn't working, removed all my resource packs and mods, still nothing. Thank you.

**Comment by Th3Dandy** [comment]
By the way, are you using something like Item Stitching fix on Vanilla Tweaks ? If yes, you actually don’t need the resource pack. The v2.0.5 works fine and as expected, but the resource pack is the issue here.
