### ISSUE TITLE
v2 port to 1.20

### ISSUE THREAD

**Issue by fibberclip** [Apollounknowndev/trimmable-tools#5]
Hey, do you have any plans of porting v2 to older versions like at least 1.20?? I'd really love to use this on an SMP i'm making but honestly having the same pattern on every single tool regardless of the trim used is pretty boring... the new system looks WAY better and it'd be a shame to have it locked to newer versions only

**Comment by Apollounknowndev** [comment]
It's being looked into, no promises yet.

**Comment by fibberclip** [comment]
i see, hope it does end up being a thing! thanks for the update!

**Comment by Apollounknowndev** [comment]
Backport released.
