### ISSUE TITLE
More Armor Trims Compatibility

### ISSUE THREAD

**Issue by Proxi2** [Apollounknowndev/trimmable-tools#7]
Any chance that in the future you could add compatibility with [More Armor Trims](https://modrinth.com/mod/more-armor-trims). If not it's all good I do realize that there's only so many pixels on a Minecraft tool and only so much time in a day 😂

**Comment by Apollounknowndev** [comment]
90 textures was painful enough, I'm not thrilled at the idea of making 50 more :P

**Comment by Proxi2** [comment]
Absolutely valid. I completely understand. Thanks for letting me know 😁
