### ISSUE TITLE
Crashing with EMI

### ISSUE THREAD

**Issue by mkern1200** [Apollounknowndev/trimmable-tools#9]
Hello!  I tried to add this mod to my pack, but it seems to cause consistent crashes with the EMI mod.  Not sure the extent of the issue, but I discovered it by accident when scrolling through the EMI menu.  At some point the game will freeze for a moment when switching to the next page of the EMI menu, and then abruptly crash.  Crash report for reference:  

[crash-2024-09-16_20.42.57-client.txt](https://github.com/user-attachments/files/17021842/crash-2024-09-16_20.42.57-client.txt)

Any help would be much appreciated!

**Comment by Apollounknowndev** [comment]
Fixed in 2.0.2.
